"""harness_tables

Revision ID: 0003
Revises: 0002
Create Date: 2026-06-13 12:35:22.368171+00:00
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_skills',
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'retired', name='skill_status'), nullable=False),
    sa.Column('pii_checked', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain', 'version', name='uq_domain_skill_version')
    )
    with op.batch_alter_table('domain_skills', schema=None) as batch_op:
        batch_op.create_index('ix_domain_skill_domain_status', ['domain', 'status'], unique=False)

    op.create_table('system_issues',
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('signals', sa.JSON(), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_issues', schema=None) as batch_op:
        batch_op.create_index('ix_system_issue_status_detected', ['status', 'detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_issues_user_id'), ['user_id'], unique=False)

    op.create_table('run_trajectories',
    sa.Column('application_id', sa.String(length=32), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('screenshots', sa.JSON(), nullable=False),
    sa.Column('agent_self_report', sa.Text(), nullable=True),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_trajectories', schema=None) as batch_op:
        batch_op.create_index('ix_run_traj_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_trajectories_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_trajectories_user_id'), ['user_id'], unique=False)

    op.create_table('skill_feedback',
    sa.Column('skill_id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=True),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['domain_skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skill_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skill_feedback_skill_id'), ['skill_id'], unique=False)

    op.create_table('run_diagnoses',
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('failure_class', sa.Enum('login_failed', 'session_expired', 'captcha_wall', 'twofa_required', 'antibot_block', 'dom_drift', 'field_missing', 'agent_offtrack', 'loop', 'llm_error', 'timeout', 'rate_limited', 'unknown', name='failure_class'), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('signals', sa.JSON(), nullable=False),
    sa.Column('suggested_action', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['run_trajectories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_diagnoses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_diagnoses_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_diagnoses_user_id'), ['user_id'], unique=False)

    op.create_table('run_verdicts',
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('verdict', sa.Enum('success', 'partial', 'failed', name='run_verdict'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('judged_model', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['run_trajectories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_verdicts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_verdicts_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_verdicts_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run_verdicts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_verdicts_user_id'))
        batch_op.drop_index(batch_op.f('ix_run_verdicts_run_id'))

    op.drop_table('run_verdicts')
    with op.batch_alter_table('run_diagnoses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_diagnoses_user_id'))
        batch_op.drop_index(batch_op.f('ix_run_diagnoses_run_id'))

    op.drop_table('run_diagnoses')
    with op.batch_alter_table('skill_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_feedback_skill_id'))

    op.drop_table('skill_feedback')
    with op.batch_alter_table('run_trajectories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_trajectories_user_id'))
        batch_op.drop_index(batch_op.f('ix_run_trajectories_application_id'))
        batch_op.drop_index('ix_run_traj_user_created')

    op.drop_table('run_trajectories')
    with op.batch_alter_table('system_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_issues_user_id'))
        batch_op.drop_index('ix_system_issue_status_detected')

    op.drop_table('system_issues')
    with op.batch_alter_table('domain_skills', schema=None) as batch_op:
        batch_op.drop_index('ix_domain_skill_domain_status')

    op.drop_table('domain_skills')
    # ### end Alembic commands ###
