"""platform_sessions

Revision ID: 0002
Revises: 0001
Create Date: 2026-06-09 12:48:48.733094+00:00
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_sessions',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('fingerprint_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'platform', name='uq_platform_session')
    )
    with op.batch_alter_table('platform_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platform_sessions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_sessions_user_id'))

    op.drop_table('platform_sessions')
    # ### end Alembic commands ###
