"""initial_tenant_schema

Revision ID: 0001
Revises: 
Create Date: 2026-06-08 18:15:59.814984+00:00
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('jobs',
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('platform_job_id', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('salary_range', sa.String(length=200), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=True),
    sa.Column('remote', sa.Boolean(), nullable=False),
    sa.Column('posted_date', sa.DateTime(), nullable=True),
    sa.Column('experience_level', sa.String(length=50), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('skills_required', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('new', 'saved', 'applied', 'hidden', name='job_status'), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'platform', 'platform_job_id', name='uq_job_platform_id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_job_match_score', ['match_score'], unique=False)
        batch_op.create_index('ix_job_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('llm_usage',
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.Enum('resume_tailor', 'cover_letter', 'ats_optimize', 'job_analysis', 'harness_judge', 'skill_distill', name='llm_purpose'), nullable=False),
    sa.Column('trace_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.create_index('ix_llm_usage_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_usage_user_id'), ['user_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.String(length=32), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('user_credentials',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('blob', sa.JSON(), nullable=False),
    sa.Column('kek_id', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'kind', 'provider', name='uq_user_credential')
    )
    with op.batch_alter_table('user_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_credentials_user_id'), ['user_id'], unique=False)

    op.create_table('user_llm_configs',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('preferred_provider', sa.String(length=50), nullable=False),
    sa.Column('fallback_providers', sa.JSON(), nullable=False),
    sa.Column('default_model', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_llm_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_llm_configs_user_id'), ['user_id'], unique=True)

    op.create_table('user_settings',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('apply_mode', sa.String(length=20), nullable=False),
    sa.Column('max_parallel', sa.Integer(), nullable=False),
    sa.Column('min_ats_score', sa.Float(), nullable=False),
    sa.Column('preferred_provider', sa.String(length=50), nullable=False),
    sa.Column('platforms_enabled', sa.JSON(), nullable=False),
    sa.Column('candidate_profile', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('resumes',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('base', 'tailored', 'optimized', name='resume_type'), nullable=False),
    sa.Column('base_resume_id', sa.String(length=32), nullable=True),
    sa.Column('job_id', sa.String(length=32), nullable=True),
    sa.Column('template_id', sa.String(length=50), nullable=False),
    sa.Column('file_path_pdf', sa.String(length=500), nullable=True),
    sa.Column('file_path_docx', sa.String(length=500), nullable=True),
    sa.Column('ats_score', sa.Float(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['base_resume_id'], ['resumes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.create_index('ix_resume_type', ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_resumes_user_id'), ['user_id'], unique=False)

    op.create_table('applications',
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('resume_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('queued', 'pending_review', 'approved', 'applying', 'applied', 'interview', 'rejected', 'offer', 'withdrawn', 'failed', name='application_status'), nullable=False),
    sa.Column('apply_mode', sa.Enum('autonomous', 'review', 'batch', name='apply_mode'), nullable=False),
    sa.Column('ats_score', sa.Float(), nullable=True),
    sa.Column('cover_letter_path', sa.String(length=500), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('response_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('browser_screenshots', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index('ix_application_job_id', ['job_id'], unique=False)
        batch_op.create_index('ix_application_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_user_id'))
        batch_op.drop_index('ix_application_status')
        batch_op.drop_index('ix_application_job_id')

    op.drop_table('applications')
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resumes_user_id'))
        batch_op.drop_index('ix_resume_type')

    op.drop_table('resumes')
    op.drop_table('user_settings')
    with op.batch_alter_table('user_llm_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_llm_configs_user_id'))

    op.drop_table('user_llm_configs')
    with op.batch_alter_table('user_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_credentials_user_id'))

    op.drop_table('user_credentials')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_family_id'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_usage_user_id'))
        batch_op.drop_index('ix_llm_usage_user_created')

    op.drop_table('llm_usage')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_user_id'))
        batch_op.drop_index('ix_job_status')
        batch_op.drop_index('ix_job_match_score')

    op.drop_table('jobs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
